### ISSUE TITLE
modinfo.json has multiline strings

### ISSUE THREAD

**Issue by JomerDev** [Serpens66/Anno-1800-Mods#1]
The modinfo.json for "Robust Kontor" has multiline strings in it, which is not allowed in json files and crashes the java modmanager

**Comment by Serpens66** [comment]
Thanks, several of my mods  may have this, because I dont use any modmanager and did not know how the format should look like. Will fix it tomorrow.

**Comment by Serpens66** [comment]
could you please test the new version? I used "/n" now for newline, but I dont know if it works.

**Comment by JomerDev** [comment]
It works now, thank you
