### ISSUE TITLE
Problem der Anzeige der Items

### ISSUE THREAD

**Issue by Wolfman237** [Serpens66/Anno-1800-Mods#3]
Habe die Mod in einem neuen Spiel eingesetzt, kein Savegame. Er zeigt mir aber an, dass nicht alle Items sofort erforscht werden können, sondern erst bei 6 Mio? Forschungspunkten. Ist das gewollt oder ein Bug?
Oder Kompatibilitätsprobleme z. B. mit anderen Mods: Combined Customizable Research and Items Mod (Taludas).
![screenshot_2023-09-25-14-21-43](https://github.com/Serpens66/Anno-1800-Mods/assets/96538401/6f1c843b-3176-45ef-bf78-49615700ba7f)

**Comment by Serpens66** [comment]
Hi,

sollte ziemlich sicher ein Modkonflikt sein, bzw. die normalen Einstellungen eines anderen Mods.
Wobeis noch hilfreich gewesen wäre, wenn du dazu schreibst welche meiner Mods in welcher Version du meinst, ich gehe mal von "Early Research Balanced" aus?

Wenn du noch nicht das vanilla Forschungszentrum gebaut hast, könntest du testweise die anderen Mods die research verändern deaktivieren und gucken ob das Problem damit beseitigt wird. Wenn du das vanilla forschungszentrum schon hast, kannst du auch meinen Mod testweise deaktivieren und gucken ob das hilft.
So findest du dann genau raus, welcher Mod dafür verantwortlich ist.

(sicherheitshalber vorher einen extra spielstand erstellen und nach den Tests diesen dann wieder laden, nicht den Spielstand in dem du getestet hast zum weierspielen nutzen, um sicherzugehen, dass weiterhin alles funktioniert)

**Comment by Serpens66** [comment]
Ah, ich glaube es geht dir um den Mod "All Items identified" ? Das macht mehr Sinn :D
Für einfacheres chatten könntest du mir auch im Discord schreiben:
https://discord.gg/nEQj3qfTYm
Am besten im "help-forum" dort einen thread aufmachen und mich taggen (Serp).

Ich glaub das Problem kommt daher:
Der Mod identifiziert einmalig alle Items die zum Zeitpunkt der erstmaligen Ausführung im Spiel sind. Du hast vermutlich danach noch Mods mit neuen Items zugefügt, diese sind dann nicht identifiziert. Und die hohen Kosten, wenn man schon so viel identifiziert hat, sind dann vermutlich normal vom Spiel vorgegeben (wobei du das sicher mit Cusomized Research auch einstellen kannst, was die max-kosten sein sollen.

Mein Lösungsvorschlag wäre jetzt, dass ich in dem Mod eine Tastenkombination einbaue, die man drücken kann, um erneut alle noch nicht identifizierten Items zu erforschen.

**Comment by Serpens66** [comment]
Habe den Mod geupdated, sowohl hier auf github als auch mod.io:
https://mod.io/g/anno-1800/m/research-all-items-identified-serp

Du kannst nun "Strg+Pos1" auf der Tatstatur drücken um damit die Identifierizierung aller items erneut zu starten.

**Comment by Wolfman237** [comment]
Hallo Serpens

 

habe das Spiel ohne deine Mod gestartet und danach nochmal mit der Mod (ohne deine Korrektur) , und der Fehler war weg.

 

Muss jetzt nur mal prüfen, woher die mehr als 100 zusätzlichen Items kommen.

 

Gruß

Wolfman

 

 

 
 

Gesendet: Dienstag, 26. September 2023 um 18:24 Uhr
Von: "Serpens66" ***@***.***>
An: "Serpens66/Anno-1800-Mods" ***@***.***>
Cc: "Wolfman237" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [Serpens66/Anno-1800-Mods] Problem der Anzeige der Items (Issue #3)


 

Habe den Mod geupdated, sowohl ihr auf github als auch mod.io:
https://mod.io/g/anno-1800/m/research-all-items-identified-serp

Du kannst nun "Strg+Pos1" auf der Tatstatur drücken um damit die Identifierizierung aller items erneut zu starten.

**Comment by Serpens66** [comment]
Das liegt daran, dass wenn du den mod deaktivierst und wieder aktivierst, der Code zum freischalten der Items erneut ausgeführt wird. also quasi genau das, was Strg+Pos1 jetzt auch macht.
