### ISSUE TITLE
Anne Harlow repariert ihren Hafen nicht

### ISSUE THREAD

**Issue by IronmanVeronika** [Serpens66/Anno-1800-Mods#4]
Ich habe deine Mods Stronger Pirates und Reward Destroy Pirate. Anne Harlow ist zwar wie von der Mod vorgesehen mit mehr und stärkeren Schiffen zurück zu ihrem Hafen gekommen und erscheint auch im  Diplomatie-Menü, aber sie repariert ihren Hafen nicht und ihre Schiffe stehen darin und machen nichts. 
Ich muss gestehen: Das war vor den Mods leider auch so. Es ist eine alte Welt und ich hoffte dass ich diesen Bug mit den Mods beheben kann. Habe schon online nach Lösungen für das Respawn-Problem gesucht aber nichts passendes gefunden.
Kannst du mir bitte Tipps geben, wie ich Anne zurück ins Spiel bekomme ohne meinen Spielfortschritt zu verlieren?
Für jegliche Hilfe bin ich sehr Dankbar.

**Comment by Serpens66** [comment]
Hi,

leider sind die Piraten massiv (in vanilla) verbuggt und es interessiert die Anno-Entscheider überhaupt nicht. Ich habe alle und noch viel mehr vanilla Bugs schon vor nem Jahr reported, doch nichts davon wurde gefixt (noch schlimmer ist dass die KI Angst vor Geschütz-Blaupausen hat).

Aber für die meisten Probleme gibt es workarounds.
Hier mal die Liste der Bugs bei den Piraten:
https://github.com/Serpens66/Anno-1800-Mods/blob/master/WorkInProgress-Mods/P%20PirateComebackFleetFix/piratecomebackfleetbugs.txt
Der Mod ist noch in Arbeit und kann verbuggt sein, also lieber noch nicht verwenden. Aber Punkt 7) wird vermutlich dein Bug sein. 

Normalerweise sollte es nun so sein, dass jedesmal wenn du dien Spielstand lädst nach der Comeback-Zeit eine weitere Piratenflotte auftaucht, richtig? Und du musst dafür sorgen, dass du im Krieg mit den Piraten bist, wenn sie auftaucht, nur dann wird alles korrekt getriggert.

**Comment by IronmanVeronika** [comment]
Ich probiere das mal. 
Ja, es tauchen immer wieder neue Schiffe auf. Ich glaube aber es dauert länger als die reguläre Comebackzeit bis neue kommen. Die reguläre Zeit ist glaub ich erst wenn ich ihren Hafen säubere. Dann kommen sie schneller, also so wie sie sollten.
Vielen Dank für die Antwort und den Tipp
